@php($editing = isset($media))
<form action="{{ $editing ? route('admin.media.update', $media) : route('admin.media.store') }}" method="POST" enctype="multipart/form-data" class="space-y-4">
@csrf @if($editing) @method('PUT') @endif
<div><label class="block text-xs font-semibold text-slate-600 mb-1">Jenis</label><select name="jenis" required class="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-sm"><option value="hero" @selected(old('jenis', $media->jenis ?? '') === 'hero')>Hero / Slideshow</option><option value="galeri" @selected(old('jenis', $media->jenis ?? '') === 'galeri')>Galeri</option></select></div>
<div><label class="block text-xs font-semibold text-slate-600 mb-1">File Gambar {{ $editing ? '(kosongkan jika tidak diganti)' : '' }}</label><input type="file" name="file" accept="image/jpeg,image/png,image/webp" {{ $editing ? '' : 'required' }} class="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-sm"></div>
<div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label class="block text-xs font-semibold text-slate-600 mb-1">Judul</label><input name="judul" value="{{ old('judul', $media->judul ?? '') }}" class="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-sm"></div><div><label class="block text-xs font-semibold text-slate-600 mb-1">Alt Text</label><input name="alt" value="{{ old('alt', $media->alt ?? '') }}" required class="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-sm"></div></div>
<div><label class="block text-xs font-semibold text-slate-600 mb-1">Caption Galeri</label><input name="caption" value="{{ old('caption', $media->caption ?? '') }}" class="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-sm"></div>
<div><label class="block text-xs font-semibold text-slate-600 mb-1">Urutan</label><input type="number" min="0" name="urutan" value="{{ old('urutan', $media->urutan ?? 0) }}" required class="w-full px-4 py-2.5 border border-slate-200 rounded-xl text-sm"></div>
<label class="flex items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" name="aktif" value="1" @checked(old('aktif', $media->aktif ?? true))> Tampilkan di halaman depan</label>
<div class="flex gap-3 pt-3"><button class="bg-teal-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold">Simpan</button><a href="{{ route('admin.media.index') }}" class="bg-slate-100 text-slate-600 px-5 py-2.5 rounded-xl text-sm font-bold">Batal</a></div>
</form>
