@extends('layouts.app')
@section('title', 'Kelola Gambar')
@section('page-title', 'KELOLA GAMBAR')
@section('sidebar-menu') @include('Admin.partials.sidebar', ['active' => 'media']) @endsection
@section('content')
<div class="flex items-center justify-between mb-6"><div><h3 class="text-lg font-bold">Gambar Hero & Galeri</h3><p class="text-xs text-slate-500 mt-1">Atur gambar slideshow dan galeri yang tampil di halaman depan.</p></div><a href="{{ route('admin.media.create') }}" class="bg-teal-600 text-white text-xs px-4 py-2.5 rounded-xl font-bold"><i class="fa-solid fa-upload mr-1"></i> Upload Gambar</a></div>
@if(session('success'))<div class="bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs p-4 rounded-xl mb-6">{{ session('success') }}</div>@endif
<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">@forelse($media as $item)<div class="bg-white rounded-2xl overflow-hidden border border-slate-100 shadow-sm"><img src="{{ $item->publicUrl() }}" alt="{{ $item->alt }}" class="w-full aspect-video object-cover"><div class="p-4"><div class="flex justify-between items-center mb-2"><span class="text-[10px] uppercase font-bold text-teal-700 bg-teal-50 px-2 py-1 rounded-full">{{ $item->jenis }}</span><span class="text-xs text-slate-400">Urutan {{ $item->urutan }}</span></div><h4 class="font-bold text-sm">{{ $item->judul ?: $item->alt }}</h4><p class="text-xs text-slate-500 mt-1">{{ $item->aktif ? 'Aktif di halaman depan' : 'Nonaktif' }}</p><div class="flex gap-2 mt-4"><a href="{{ route('admin.media.edit', $item->id) }}" class="bg-amber-500 text-white text-xs px-3 py-2 rounded-lg">Edit</a><form action="{{ route('admin.media.destroy', $item->id) }}" method="POST" onsubmit="return confirm('Hapus gambar ini?')">@csrf @method('DELETE')<button class="bg-rose-500 text-white text-xs px-3 py-2 rounded-lg">Hapus</button></form></div></div></div>@empty<div class="col-span-full bg-white p-8 text-center text-sm text-slate-400 rounded-2xl">Belum ada gambar.</div>@endforelse</div>
@endsection
